deployment:
  tasks:
    - export REPOPATH=/home/favorit-original/*
    - export SITEPATH=/home/faershoe/i.shoesbar.by/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH

